apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 12
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: main
          image: ghcr.io/sika-training-examples/egd-processor
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: kafka-kafka-bootstrap.kafka.svc:9092
            - name: KAFKA_SOURCE_TOPIC
              value: foo
            - name: KAFKA_SOURCE_GROUP
              value: foo
            - name: KAFKA_TARGET_TOPIC
              value: bar
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
